import "./index.scss";
import webp1 from "./assets/1.webp";
import webp2 from "./assets/2.webp";
import webp3 from "./assets/3.webp";
import webp4 from "./assets/4.webp";
import webp5 from "./assets/5.webp";
import webp6 from "./assets/6.webp";
import webp7 from "./assets/7.webp";
import webp8 from "./assets/8.webp";
import alpost from "./assets/alpost.mkv";
import cveng from "./assets/CV_Piotr_Górski_eng_noTel.pdf";
import cvpl from "./assets/CV_Piotr_Górski_pl_noTel.pdf";
import dyplom from "./assets/dyplom.jpg";
import hala from "./assets/hala.jpeg";
import kot from "./assets/kot.jpg";
import kot2 from "./assets/kot2.jpg";
import logoblack from "./assets/LOGO_black.png";
import logowhite from "./assets/LOGO_white.png";
import magistera from "./assets/magistera.jpg";
import musicalia from "./assets/Musicalia.mp4";
import myimage from "./assets/my-image.png";
import plaza from "./assets/plaza.jpg";
import task1 from "./assets/task1.webp";
import task2 from "./assets/task2.webp";
import task3 from "./assets/task3.webp";
import xkom from "./assets/x-kom_clone_video.mkv";
import favicon from "./assets/favicon-70.png";
import archImages from "./javascript/archImages";
import arrows from "./javascript/arrows";
import navbar from "./javascript/navbar";
import projects from "./javascript/projects";
import spaceBackground from "./javascript/spaceBackground";
import colorTheme from "./javascript/colorTheme";

spaceBackground();
navbar();
arrows();
projects();
archImages();
colorTheme();
